### ISSUE TITLE
 [ID0010] Change operation multisig threshold from 3 to 2

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#11]
[Date] 20230412
[State] Success
[Priority] High
[Network] Tezos mainnet
[Version] Tezos-client 16.1

#Transaction description
Change operation multisig threshold from 3 to 2.
Public key remain the same:
- 0 : edpktg21XqcoUhi2AShyooCc43gQaZjGmHVFiinzdrRDqs2tQAXtv3 (Ben's ledger public key)
- 1 : edpkutwUGf7uXSmf6pfZPpgELKC5wJAKChJGVS82fp9GZEwQPvCcv6 (Gabe's ledger public key)
- 2 : edpkuqBpGBj5hdZ1Lf6DHR7TwVxrU3qe8E9n8wQRnmvPyHYhggML4R (Chris's ledger public key)

**Comment by shapeman** [comment]
# Generated transaction
```python
Pair (Pair 0x7a06a770 0x01c3273e0b48292e3958c4002eecb6f90c19abcbe000)
     (Pair 5
           (Right
              (Pair 2
                    { 0x00041306c9bf291e5f173aee24a373803469a6ff42e5907f4b2214f2d43e01bc08 ;
                      0x00a51c5e332bbd7153be5e31a3570572f0b667c2bba2ae70cae5378c0f6ebf72ad ;
                      0x009c970393d87a32dfac113c5c070bd6ea57c534dce5c88be3f6d7cf2dc3d51973 })))
```

# Bytes to sign
```
0x05070707070a000000047a06a7700a0000001601c3273e0b48292e3958c4002eecb6f90c19abcbe0000707000505080707000202000000720a0000002100041306c9bf291e5f173aee24a373803469a6ff42e5907f4b2214f2d43e01bc080a0000002100a51c5e332bbd7153be5e31a3570572f0b667c2bba2ae70cae5378c0f6ebf72ad0a00000021009c970393d87a32dfac113c5c070bd6ea57c534dce5c88be3f6d7cf2dc3d51973
```

**Comment by decentralgabe** [comment]
# Signatures
- [ ] Ben:
- [x] Gabe: ```edsigthm81U9wZ7GWKFDsQ65g69Mjr8UYhSMysDNCtfWz4pF9oDno3XXZNuxC6DLQW7m98TXZaSuXBpbm1WuAjTQ3HFUfapBjKp```
- [x] Chris: ```edsigtf1m947NtpHhu9GVmBrfXtmwctuu6aYADneojBzDuakbrjEoy51kJpumabxEgVwhV5mjDjEDJsZ5D8qTvdohP8LpSxrm7J```

**Comment by benwhately** [comment]
> # Signatures
> * [x ]  Ben: edsigtfMh8GxaFJtUmWF3heHhroNuxsPDX5kWDGciocWiLd237tts7nXuWbwrQvzJxqUy9xuPk239aDKv2WcbBj1mshXcgzFQcM
> * [x]  Gabe: `edsigthm81U9wZ7GWKFDsQ65g69Mjr8UYhSMysDNCtfWz4pF9oDno3XXZNuxC6DLQW7m98TXZaSuXBpbm1WuAjTQ3HFUfapBjKp`
> * [x]  Chris: `edsigtf1m947NtpHhu9GVmBrfXtmwctuu6aYADneojBzDuakbrjEoy51kJpumabxEgVwhV5mjDjEDJsZ5D8qTvdohP8LpSxrm7J`

**Comment by shapeman** [comment]
Successful 20230412 at 10.45pm
