### ISSUE TITLE
 [ID0011] Change swap multisig threshold from 3 to 2 #11 

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#12]
[Date] 20230412
[State] Success
[Priority] High
[Network] Tezos mainnet
[Version] Tezos-client 16.1

#Transaction description
Change swap multisig threshold from 3 to 2 (KT1Vpe5mJ6n2g9gxzmMCZNPjZkN5utnwZwd8).
Public key remain the same:
- 0 : edpktg21XqcoUhi2AShyooCc43gQaZjGmHVFiinzdrRDqs2tQAXtv3 (Ben's ledger public key)
- 1 : edpkutwUGf7uXSmf6pfZPpgELKC5wJAKChJGVS82fp9GZEwQPvCcv6 (Gabe's ledger public key)
- 2 : edpkuqBpGBj5hdZ1Lf6DHR7TwVxrU3qe8E9n8wQRnmvPyHYhggML4R (Chris's ledger public key)

**Comment by shapeman** [comment]
# Generated transaction
```python
Pair (Pair 0x7a06a770 0x01e8fa37f76f45a99be8c1e0b627d58f0787c4b6b200)
     (Pair 4
           (Right
              (Pair 2
                    { 0x00041306c9bf291e5f173aee24a373803469a6ff42e5907f4b2214f2d43e01bc08 ;
                      0x00a51c5e332bbd7153be5e31a3570572f0b667c2bba2ae70cae5378c0f6ebf72ad ;
                      0x009c970393d87a32dfac113c5c070bd6ea57c534dce5c88be3f6d7cf2dc3d51973 })))
```

# Bytes to sign
```0x05070707070a000000047a06a7700a0000001601e8fa37f76f45a99be8c1e0b627d58f0787c4b6b2000707000405080707000202000000720a0000002100041306c9bf291e5f173aee24a373803469a6ff42e5907f4b2214f2d43e01bc080a0000002100a51c5e332bbd7153be5e31a3570572f0b667c2bba2ae70cae5378c0f6ebf72ad0a00000021009c970393d87a32dfac113c5c070bd6ea57c534dce5c88be3f6d7cf2dc3d51973```

**Comment by shapeman** [comment]
- [ ] Ben:
- [ ] Gabe:
- [ ] Chris:

**Comment by decentralgabe** [comment]
- [ ] Ben:
- [x] Gabe: ```edsigu7Bkw4ujabKgteEgUprsJpVpfjHtfTU93YNXbEmvo3qwq21XvFPXxXUPC5bFQp49KawidHvtcz2wpfJNbw3eQNVTr9bLaA```
- [x] Chris: ```edsigtmA5e7x5m9tFiwFX6UYLpqsTDgGpkLeSsXbrKJpaLCuJrMj374KA8UdADGiHTRpowT5csWEjcV6y8G2Ft4SW1ZzgPnECbQ```

**Comment by benwhately** [comment]
> * [x]  Ben:  `edsigtjYbsL46ubGKzsWcuNMWsH2EGdd9bRq7RK42sCB4Cozhis7cDLTFfa5TkqaoKV8iowcqPieEnKXf7ufYEgUDtAG5Cg7Zrc`
> * [x]  Gabe: `edsigu7Bkw4ujabKgteEgUprsJpVpfjHtfTU93YNXbEmvo3qwq21XvFPXxXUPC5bFQp49KawidHvtcz2wpfJNbw3eQNVTr9bLaA`
> * [x]  Chris: `edsigtmA5e7x5m9tFiwFX6UYLpqsTDgGpkLeSsXbrKJpaLCuJrMj374KA8UdADGiHTRpowT5csWEjcV6y8G2Ft4SW1ZzgPnECbQ`

**Comment by shapeman** [comment]
Success 20230414 at 5.23pm
