### ISSUE TITLE
 [ID0012] Change admin of the sale contract

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#13]
# Description

[Date] 20230413
[State] Success
[Priority] Medium
[Network] Tezos mainnet
[Version] Tezos-client 16.1

The admin of the sale contract shall be the operation multisig (KT1SNeLn9mp1f5dDyP1x4mnyAFY7wjHtJ7mt) and not the dummy address we used to deploy.

**Comment by shapeman** [comment]
# Generated lambda
```python
{ { DROP ;
    NIL operation ;
    PUSH address 0x018e013941733e9ab51a446cfa14c32d0a839b334b00 ;
    CONTRACT %validate_new_administrator unit ;
    IF_NONE { PUSH int 16 ; FAILWITH } {} ;
    PUSH mutez 0 ;
    UNIT ;
    TRANSFER_TOKENS ;
    CONS } }
```

# Bytes to sign
```
0x05070707070a000000047a06a7700a0000001601c3273e0b48292e3958c4002eecb6f90c19abcbe000070700060505020000006d02000000680320053d036d0743036e0a00000016018e013941733e9ab51a446cfa14c32d0a839b334b000655036c0000001b2576616c69646174655f6e65775f61646d696e6973747261746f72072f02000000080743035b0010032702000000000743036a0000034f034d031b
```

**Comment by shapeman** [comment]
# Signatures (2 out of 3 is needed)
- [ ] Ben:
- [ ] Gabe:
- [ ] Chris:

**Comment by benwhately** [comment]
> # Signatures (2 out of 3 is needed)
> * [x]  Ben: `edsigtdEe9hD2ZGLfPM6UruAxwEz9uW11qndcLjD3CCLF6JzEHJwudH3ndcDcC1rKrzeXd2jRXVrMrpsvm3ctsNEVS5ah9Rg8D2`
> * [ ]  Gabe:
> * [x]  Chris: `edsigtyMVezm9yVPR1cpr3p6zG4ur3zjEMTYqBxf8ru2e76ux27RE3zcomGx1GNHzSZ9VbSzFtYNFL4qs2mmbF3A7tKj5S16awa`

**Comment by shapeman** [comment]
Succesful. 20120413 at 11.03am
