### ISSUE TITLE
 [ID0013] Change admin of the NFT contract

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#14]
# Description

[Date] 20230413
[State] Success
[Priority] Medium
[Network] Tezos mainnet
[Version] Tezos-client 16.1

The admin of the NFT contract shall be the operation multisig (KT1SeAGLZJQoXd2Qc3jbV6ddpFvWP9UY7vxq) and not the dummy address we used to deploy.

**Comment by shapeman** [comment]
# Signatures (2 out of 3 are needed)
- [ ] Ben:
- [ ] Gabe:
- [ ] Chris:

**Comment by benwhately** [comment]
[x] Ben: `edsigtjSooaoREzLU5dov7X6ktHUUXjsfkZwbfpSVNLBHD2T23Q2FNmeSHdQkURHkNUMrzCU1nXpb3YGx94bVfK118vQ4aZ6FEC`
 Gabe:
 Chris:

**Comment by shapeman** [comment]
Success 20230414 at 5.30pm
