### ISSUE TITLE
 [ID0014] Change admin of the main DAO contract

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#15]
# Description

[Date] 20230414
[State] Success
[Priority] Medium
[Network] Tezos mainnet
[Version] Tezos-client 16.1

The admin of the man DAO contract (KT1ABmuaZjRizQn4ZfdwDHF9Rn2UoXeqkKia) shall be the operation multisig  (KT1SNeLn9mp1f5dDyP1x4mnyAFY7wjHtJ7mt) and not the dummy address we used to deploy.

**Comment by shapeman** [comment]
# Generated lambda
```python
{ { DROP ;
    NIL operation ;
    PUSH address 0x011196f838eb69210e908e77a9dd67e2a27ee7f90d00 ;
    CONTRACT %validate_new_administrator unit ;
    IF_NONE { PUSH int 16 ; FAILWITH } {} ;
    PUSH mutez 0 ;
    UNIT ;
    TRANSFER_TOKENS ;
    CONS } }
```

# Bytes to sign
```
0x05070707070a000000047a06a7700a0000001601c3273e0b48292e3958c4002eecb6f90c19abcbe000070700080505020000006d02000000680320053d036d0743036e0a00000016011196f838eb69210e908e77a9dd67e2a27ee7f90d000655036c0000001b2576616c69646174655f6e65775f61646d696e6973747261746f72072f02000000080743035b0010032702000000000743036a0000034f034d031b
```

**Comment by shapeman** [comment]
# Signatures (2 out of 3 needed)
- [ ] Ben:
- [ ] Gabe:
- [ ] Chris

**Comment by benwhately** [comment]
> # Signatures (2 out of 3 needed)
> * [x]  Ben: `edsigthcacBYszoCPt4w1LT9ewKDsGbqGc4j7usHVqaaE18Kq7BKq4dcCSFpsq6tcZAEyMrb7buUQywzUMYT7wkMZVa9NmUYRpH`
> * [ ]  Gabe:
> * [x]  Chris: `edsigtn8TFw7hSKzY2XRmrnbxv3vyUXGFjruahH6t9axXyXVHrw6Mhkihgm7BRJncY2wcJAU6iKU3ne9ph3kNFJWmjkJheUwQ6u`

**Comment by shapeman** [comment]
Success 20230416 at 1.40pm
