### ISSUE TITLE
 [ID0015] Change admin of the main majority contract

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#16]
# Description

[Date] 20230416
[State] Success
[Priority] Medium
[Network] Tezos mainnet
[Version] Tezos-client 16.1

The admin of the majority main DAO contract (KT1ELDcwh28FiToEbGcA4qzenwLoBP9Lbk4c) shall be the operation multisig  (KT1SNeLn9mp1f5dDyP1x4mnyAFY7wjHtJ7mt) and not the dummy address we used to deploy.

**Comment by shapeman** [comment]
# Generated lambda
```python
{ { DROP ;
    NIL operation ;
    PUSH address 0x013f1043c521999ea9e52be3b469ebba533d97f6e400 ;
    CONTRACT %validate_new_administrator unit ;
    IF_NONE { PUSH int 16 ; FAILWITH } {} ;
    PUSH mutez 0 ;
    UNIT ;
    TRANSFER_TOKENS ;
    CONS } }
```

# Bytes to sign
```
0x05070707070a000000047a06a7700a0000001601c3273e0b48292e3958c4002eecb6f90c19abcbe000070700090505020000006d02000000680320053d036d0743036e0a00000016013f1043c521999ea9e52be3b469ebba533d97f6e4000655036c0000001b2576616c69646174655f6e65775f61646d696e6973747261746f72072f02000000080743035b0010032702000000000743036a0000034f034d031b
```

**Comment by benwhately** [comment]
- [x] Ben: edsigtZxbAp1BnacA2rzqEXVAjLoyatXYmyAFoGcTMsayTkirWnRn62xMQatt7ZqQuqYEqwviW1cHHnjM5TWkUjVboR2wkrkqS4
- [ ] Gabe
- [ ] Christophe

**Comment by shapeman** [comment]
Success 20230425 at 2.30pm
