### ISSUE TITLE
 [ID0016] Change admin of the main opt out contract

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#17]
# Description

[Date] 20230416
[State] Success
[Priority] Medium
[Network] Tezos mainnet
[Version] Tezos-client 16.1

The admin of the majority main opt out DAO contract (KT1UiSy3WTLqWsYQLri3UmbxVQd65o6qMsrF) shall be the operation multisig  (KT1SNeLn9mp1f5dDyP1x4mnyAFY7wjHtJ7mt) and not the dummy address we used to deploy.

**Comment by shapeman** [comment]
# Generated lambda
```python
{ { DROP ;
    NIL operation ;
    PUSH address 0x01dcd65168b138caf295b91160bd9e999f0cc3358100 ;
    CONTRACT %validate_new_administrator unit ;
    IF_NONE { PUSH int 16 ; FAILWITH } {} ;
    PUSH mutez 0 ;
    UNIT ;
    TRANSFER_TOKENS ;
    CONS } }
```

# Bytes to sign
```
0x05070707070a000000047a06a7700a0000001601c3273e0b48292e3958c4002eecb6f90c19abcbe0000707000a0505020000006d02000000680320053d036d0743036e0a0000001601dcd65168b138caf295b91160bd9e999f0cc33581000655036c0000001b2576616c69646174655f6e65775f61646d696e6973747261746f72072f02000000080743035b0010032702000000000743036a0000034f034d031b
```

**Comment by shapeman** [comment]
# Signatures (2 out of 3 needed)

- [ ] Ben:
- [ ] Gabe:
- [ ] Chris:

**Comment by benwhately** [comment]
> # Signatures (2 out of 3 needed)
> * [x]  Ben: `edsigteSu4HhHG8F8B2Jgmtep9nbyPGDErS8KZk1iXHgy27TdmtSudKREWjaywv5mXAfMo2rmf95P2CBCtc3R1KhAFyVoA3Szub`
> * [ ]  Gabe:
> * [x]  Chris: `edsigtpdfjRC42c3dgkMKSapDV4eBB222MMfLBH8oHSikGP6hsPbz5m91SVt7VkhByANrA6bKngi2w8mfgzCX6Jf4xNg7CZzmwX`

**Comment by shapeman** [comment]
Success 20230416 at 5.06pm
