### ISSUE TITLE
 [ID0017] Change admin of the majority opt out contract

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#18]
# Description

[Date] 20230416
[State] Success
[Priority] Medium
[Network] Tezos mainnet
[Version] Tezos-client 16.1

The admin of the majority opt out majority DAO contract (KT1UiSy3WTLqWsYQLri3UmbxVQd65o6qMsrF) shall be the operation multisig  (KT1SNeLn9mp1f5dDyP1x4mnyAFY7wjHtJ7mt) and not the dummy address we used to deploy.

**Comment by shapeman** [comment]
# Generated lambda
```python
{ { DROP ;
    NIL operation ;
    PUSH address 0x01911fde95a92cb01ab848b0983313c2a02b50fb7c00 ;
    CONTRACT %validate_new_administrator unit ;
    IF_NONE { PUSH int 16 ; FAILWITH } {} ;
    PUSH mutez 0 ;
    UNIT ;
    TRANSFER_TOKENS ;
    CONS } }
```

# Bytes to sign
```
0x05070707070a000000047a06a7700a0000001601c3273e0b48292e3958c4002eecb6f90c19abcbe0000707000b0505020000006d02000000680320053d036d0743036e0a0000001601911fde95a92cb01ab848b0983313c2a02b50fb7c000655036c0000001b2576616c69646174655f6e65775f61646d696e6973747261746f72072f02000000080743035b0010032702000000000743036a0000034f034d031b
```

**Comment by shapeman** [comment]
# Signatures (2 out of 3 are needed)
- [ ] Ben:
- [ ] Gabe:
- [ ] Chris:

**Comment by benwhately** [comment]
> # Signatures (2 out of 3 are needed)
> * [x]  Ben: `edsigteQvKfv6Z9aeM1wawLkvJyWQhTbkFXq4YpSKqYiYpmhGBjQ1gYWE6PaTmBTVjqyhEd9C81AN9pDbBwmnqf9pyCiPudXyYW
> * [ ]  Gabe:
> * [ ]  Chris: `edsigtcJB8wQmyuRqboXGzo3wctvhkQRsVUjxi2hrdmiU4Pf8MmkbmpGsgDLmgdY1UvFQqRBxcAgGxgsfHBesBsRfMjSNftXeRy`

**Comment by shapeman** [comment]
Success 20230417 at 7.45pm
