### ISSUE TITLE
 [ID0019] Fill allowlist for presale holder

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#20]
# Description

[Date] 20230422
[State] Success
[Priority] Medium
[Network] Tezos mainnet
[Version] Tezos-client 16.1

Transfer 1200 USDT to mint the AT PIlot tokens for the presale holders from the swap multisig (KT1Vpe5mJ6n2g9gxzmMCZNPjZkN5utnwZwd8).
USDT Tether Tezos contract address is: KT1XnTn74bUtxHfDtBmm2bGZAQfhPbvKWR8o

**Comment by shapeman** [comment]
# Generated lambda
```python
{ { DROP ;
    NIL operation ;
    PUSH address 0x01fe810959c3d6127a41cbd471e7cb4e91a61b780b00 ;
    CONTRACT %transfer (list (pair address (list (pair address (pair nat nat))))) ;
    IF_NONE { PUSH int 16 ; FAILWITH } {} ;
    PUSH mutez 0 ;
    PUSH (list (pair address (list (pair address (pair nat nat)))))
         { Pair 0x01e8fa37f76f45a99be8c1e0b627d58f0787c4b6b200
                { Pair 0x00003912af8820e7942f731038c0dacaf52cd045f60c (Pair 0 1200) } } ;
    TRANSFER_TOKENS ;
    CONS } }
```

# Bytes to sign
```
0x05070707070a000000047a06a7700a0000001601e8fa37f76f45a99be8c1e0b627d58f0787c4b6b20007070005050502000000c802000000c30320053d036d0743036e0a0000001601fe810959c3d6127a41cbd471e7cb4e91a61b780b000655055f0765036e055f0765036e07650362036200000009257472616e73666572072f02000000080743035b0010032702000000000743036a00000743055f0765036e055f0765036e076503620362020000004607070a0000001601e8fa37f76f45a99be8c1e0b627d58f0787c4b6b200020000002407070a0000001600003912af8820e7942f731038c0dacaf52cd045f60c0707000000b012034d031b
```

**Comment by shapeman** [comment]
# Signatures (2 out 3 needed)
- [ ] Ben:
- [ ] Gabe
- [ ] Chris:

**Comment by benwhately** [comment]
> # Signatures (2 out 3 needed)
> * [x]  Ben: `edsigu6AY9Lsxb2ZpRJHBvAxJZApe7yB6c9vbmiPu1iHgvy7UeedxqAwAqTx6xnnPVtW2TAjQrtvm4ZQ4E4ahiEhXFe6qJmafLX`
> * [ ]  Gabe
> * [ ]  Chris:

**Comment by benwhately** [comment]
> # Signatures (2 out 3 needed)
> * [x]  Ben: `edsigtopusLZUms9NJNyG3moxf2BDxjJ7ErnK8CwjiYDUV6ynLJJyNkykFNmR1XepQThejuWaDnfHbz1LQyuRYtP6ZN6Pr2b54F`
> * [ ]  Gabe
> * [x]  Chris: `edsigtyUZiSuuMVcAAhSpnSCcCcEbAMm3nQeEpsTNw2vFuWAr1ZPzDzGM9pACtwxyZe3S2mngGb6t4UFBuLSy3Hg7SSqbw5sE2C`

**Comment by benwhately** [comment]
> # Signatures (2 out 3 needed)
> * [x]  Ben: `edsigtauyAtdXsmCr1U6cpk664kcnPyLpT7rsWJDovx7BDdDdYMfbYxcDPHJjJNwQ8boZdimMHMn5czKeGrytskmLVD2WpE9JBw`
> * [ ]  Gabe
> * [x]  Chris: `edsigthczAaDFo88whpNbG4BHj2buY3QZ1jPdNZAbRJoD12Ut5zdPA2yPNhWL4UC4yLStBS2JDSGFYKnhQFXxahRp8cpFSbHbho`

**Comment by shapeman** [comment]
Sucess 20230422 at 11.45am
