### ISSUE TITLE
 [ID0020] Open sale with allowlist

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#21]
# Description

[Date] 20230422
[State] Success
[Priority] Medium
[Network] Tezos mainnet
[Version] Tezos-client 16.1

Open a private sale with allowlist on the sale contract (KT1MXcz2Uw2UXAkxjLLy2Z37MxDk4sfaKvty) for the Pilot project.
60 NFTS supplies, 32 max per owner. 20 Tez per token.

**Comment by shapeman** [comment]
# Generated lambda
```python
{ { DROP ;
    NIL operation ;
    PUSH address 0x018e013941733e9ab51a446cfa14c32d0a839b334b00 ;
    CONTRACT %open_pre_sale (pair nat (pair nat mutez)) ;
    IF_NONE { PUSH int 16 ; FAILWITH } {} ;
    PUSH mutez 0 ;
    PUSH (pair nat (pair nat mutez)) (Pair 32 (Pair 60 20000000)) ;
    TRANSFER_TOKENS ;
    CONS } }
```

# Bytes to sign
```
0x05070707070a000000047a06a7700a0000001601c3273e0b48292e3958c4002eecb6f90c19abcbe0000707000d0505020000007f020000007a0320053d036d0743036e0a00000016018e013941733e9ab51a446cfa14c32d0a839b334b0006550765036207650362036a0000000e256f70656e5f7072655f73616c65072f02000000080743035b0010032702000000000743036a000007430765036207650362036a070700200707003c0080b48913034d031b
```

**Comment by shapeman** [comment]
# Signatures (2 out 3 needed):
- [ ] Chris: ``` ```

**Comment by benwhately** [comment]
> # Signatures (2 out 3 needed):
> * [x] Ben: `edsigtkeJbrdtGWcxHWCJPdTsjNsa8dP5UxXRfvoDmmFQeSYGgqdHC6nuAfRqwH8HcjkvPhm5oZCYSbVU6ZvuVWXHHz6TCj5ZUe`
> * [ ]  Chris: `edsigtpP4FxRN2xNiSveCZthBWfUMQcd1YVg9SM36bhxXWevG6s4W22nQRatecKpiWQzaj5QmZ4j8HiyJLXWzCLcjzvXAz3aYWY`

**Comment by shapeman** [comment]
Success
