### ISSUE TITLE
[ID0021] Close the sale with allowlist

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#22]
[Date] 20221102
[State] Successfull
[Priority] Medium
[Network] Tezos mainnet
[Version] Tezos-client 16.1

Close the presale opened to mint Pilot ATs for presale holders

**Comment by shapeman** [comment]
# Generated lambda
```python
{ { DROP ;
    NIL operation ;
    PUSH address 0x018e013941733e9ab51a446cfa14c32d0a839b334b00 ;
    CONTRACT %close_any_open_event unit ;
    IF_NONE { PUSH int 16 ; FAILWITH } {} ;
    PUSH mutez 0 ;
    UNIT ;
    TRANSFER_TOKENS ;
    CONS } }
```

# Bytes to sign
```
0x05070707070a000000047a06a7700a0000001601c3273e0b48292e3958c4002eecb6f90c19abcbe0000707000e0505020000006702000000620320053d036d0743036e0a00000016018e013941733e9ab51a446cfa14c32d0a839b334b000655036c0000001525636c6f73655f616e795f6f70656e5f6576656e74072f02000000080743035b0010032702000000000743036a0000034f034d031b
```

**Comment by shapeman** [comment]
# Signatures (2 out of 3 needed)
- [ ] Chris: ```edsigtgL875k18kGF3fxzKsAWUAVg3FkxfwhfDcxvSf87pbRRkveeaxVxozeT6V1frBaUscVpKQXqLPu2jXfjT28WnKBs2nQi99```

**Comment by benwhately** [comment]
> # Signatures (2 out of 3 needed)
> * [ ]  Chris: `edsigtgL875k18kGF3fxzKsAWUAVg3FkxfwhfDcxvSf87pbRRkveeaxVxozeT6V1frBaUscVpKQXqLPu2jXfjT28WnKBs2nQi99`
> * [x] Ben `edsigtjqjenkrk7qgZmx83XANh6BY1ybJjyN45KA7oFhGMMwARBCr5vLpERZBouTPsK4NJbBa9TX32zKgK8hBxhLcZ3qMh4unKj`

**Comment by shapeman** [comment]
Success 20230422 at 2.18pm
