### ISSUE TITLE
[ID0022] Transfer 1200 XTZ from swap wallet to binance address tz1fUFYvA4bdw1zxhhJWfZi7K5urLLJ3NzKF

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#23]
[Date] 20220422
[State] Successfull
[Priority] Medium
[Network] Tezos mainnet
[Version] Tezos-client 16.1

Send 1200 Tez from the swap wallet to binance for USDT swap.
Multisig used: KT1Vpe5mJ6n2g9gxzmMCZNPjZkN5utnwZwd8 ( EcoMint swap wallet multisig)
Target binance address: tz1fUFYvA4bdw1zxhhJWfZi7K5urLLJ3NzKF

**Comment by shapeman** [comment]
# Generated lambda
```python
{ { DROP ;
    NIL operation ;
    PUSH address 0x0000d98917017d211b8072a52b4448ee407b4bd04f9d ;
    CONTRACT unit ;
    IF_NONE { PUSH int 7 ; FAILWITH } {} ;
    PUSH mutez 1200000000 ;
    UNIT ;
    TRANSFER_TOKENS ;
    CONS } }
```

# Bytes to sign
```
0x05070707070a000000047a06a7700a0000001601c3273e0b48292e3958c4002eecb6f90c19abcbe0000707000f05050200000052020000004d0320053d036d0743036e0a000000160000d98917017d211b8072a52b4448ee407b4bd04f9d0555036c072f02000000080743035b0007032702000000000743036a0080b0b4f808034f034d031b
```

**Comment by shapeman** [comment]
# Signatures (2 out of 3)
Chris: ```edsigtuGn7hcJd7PyWVETW2Kwx35KjdsS6UaJk9fNt7Ai7bEQXZPsTmMhWsLrGMNMYZGG8Jdv6CpnkQLEko31mTydXiqfFKAsp3```

**Comment by benwhately** [comment]
> 
 * [x] Ben: `edsigtkYeGqDCPyBVNpHcGUu5g1bEZNdH2qk43JUZtZXdjRm29n4z6Tm3D8dV5Jv8k3o9SWTz5pCDU317BmddMjJGMTWoU9he2V`

**Comment by benwhately** [comment]
> # Signatures (2 out of 3)
> Chris: `edsigtgeBnYU1oxp6tSwds8jAZgN4ypKpjNG2v6DyH6yzELCYKxfcHJE4NKTRCe7pbL1qNHAWKvcH8YDtCAEfPQ4Ai4jGDaKnAK`
> Ben `edsigtxAJSH6tSHwVT5baqqH7LFMko9zQicHVZCTwqpTxAw8y2WvDeJvaPvWrGVPN4m8fx8GvfQcRDeqQHg9kjHhUPfWU2856yS`

**Comment by shapeman** [comment]
Success 20230422 at 3.14pm
