### ISSUE TITLE
[ID0023] Set artwork admin to be the operation multisig

### ISSUE THREAD

**Issue by shapeman** [eco-mint/angry-teenagers-multisig-cli#24]
[Date] 20230422
[State] Successfull
[Priority] Medium
[Network] Tezos mainnet
[Version] Tezos-client 16.1

Set artwork admin of the NFT contract of the AT Pilot project (KT1SeAGLZJQoXd2Qc3jbV6ddpFvWP9UY7vxq) to be the operation multisig (KT1SNeLn9mp1f5dDyP1x4mnyAFY7wjHtJ7mt)

**Comment by shapeman** [comment]
# Generated lambda
```python
{ { DROP ;
    NIL operation ;
    PUSH address 0x01c61675ea3114c1cf85c981ba426a6bb0fd3687b900 ;
    CONTRACT %set_artwork_administrator address ;
    IF_NONE { PUSH int 16 ; FAILWITH } {} ;
    PUSH mutez 0 ;
    PUSH address 0x01c3273e0b48292e3958c4002eecb6f90c19abcbe000 ;
    TRANSFER_TOKENS ;
    CONS } }
```

# Bytes to sign
```
0x05070707070a000000047a06a7700a0000001601c3273e0b48292e3958c4002eecb6f90c19abcbe0000707000f0505020000008902000000840320053d036d0743036e0a0000001601c61675ea3114c1cf85c981ba426a6bb0fd3687b9000655036e0000001a257365745f617274776f726b5f61646d696e6973747261746f72072f02000000080743035b0010032702000000000743036a00000743036e0a0000001601c3273e0b48292e3958c4002eecb6f90c19abcbe000034d031b
```

**Comment by shapeman** [comment]
# Signatures (2 out of 3 needed)
- Chris: ```edsigte52dgVUcioMeiso3ZcGw8MJtiSzShzbAmB9RXB7cNU443osZ64kKzFxQCQhf8ReJQ6XQm317qnivBQ543MQqD12Bn5nSR```

**Comment by benwhately** [comment]
> # Signatures (2 out of 3 needed)
> * Chris: `edsigte52dgVUcioMeiso3ZcGw8MJtiSzShzbAmB9RXB7cNU443osZ64kKzFxQCQhf8ReJQ6XQm317qnivBQ543MQqD12Bn5nSR`

> * Ben: `edsigtcZAAMJxVDbhp5dVUDtjPd5BvdrY6PmuesfCU5NCbWd8uafaJ75517a25QZFj4tes1RijG3AdiEaGRpG4xidfqaEZTP6Eh`

**Comment by shapeman** [comment]
Success 20230423 at 3.18pm
